import Head from "next/head";
import { Box, useColorModeValue } from "@chakra-ui/react";
import Loader from "../components/Loader";
import { useEffect, useState } from "react";
import PortfolioPage from "../components";

export default function Home() {
	const [isLoading, setIsLoading] = useState(false);

	useEffect(() => {
		setIsLoading(true);
		setTimeout(() => {
			setIsLoading(false);
		}, 8000);
	}, []);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box bg={useColorModeValue("white", "black")} height={"100vh"}>
				{isLoading ? <Loader /> : <PortfolioPage />}
			</Box>
		</>
	);
}
